version: '2.4.3.{build}’

image:
	- Visual Studio 2019
	- macos

# Do not build on tags (GitHub only)
skip_tags: true

branches:
  only:
  - master

#environment:
#  GITHUB_TOKEN:
#    secure: 9UB76Z8mCWYt1u7Ci2fPVNiI3iK3LzTuIPhtNGBbxKP7YOPaUuq2yHxRjIfRPEAx
#  UPLOADTOOL_BODY:
#    "WARNING: pre-release builds may not work. Use at your own risk.”

#artifacts:
#  - path: 'src\artisan-*.zip'

for:
#  -
#	matrix:
#	    only:
#                - image: Visual Studio 2019
#
#	environment:
#	    PYTHON: "C:\\Python38-x64”
#	    PYTHON_VERSION: 3.8.x
#	    ARTISAN_VERSION: 2.4.3
##		[…]
#
#
#    install:
#  - export GIT_VERSION=`git rev-parse --verify --short HEAD 2>/dev/null|| echo "???"`
#  - sed -i'' -e "s/__revision__ = '0'/__revision__ = '$GIT_VERSION'/" src/artisanlib/__init__.py
#  - .travis/install-${ARTISAN_OS}.sh
#
#    build_script:
#  - .travis/script-${ARTISAN_OS}.sh
#
##    deploy_script:
##    <existing script>

  -
	matrix:
	    only:
           - image: macos

	environment:

    - ARTISAN_OS=osx
    osx_image: xcode10.1 # Xcode 10.1, macOS 10.13
    python: 3.8
    language: generic

    install:
  - export GIT_VERSION=`git rev-parse --verify --short HEAD 2>/dev/null|| echo "???"`
  - sed -i'' -e "s/__revision__ = '0'/__revision__ = '$GIT_VERSION'/" src/artisanlib/__init__.py
  - .travis/install-${ARTISAN_OS}.sh

    build_script:
  - .travis/script-${ARTISAN_OS}.sh

#    deploy_script:
#    <macOS script>



## invalid language: python
#
## safelist
#branches:
#  only:
##  - gh-pages
#  - master
#
##addons:
##  apt:
##    packages:
##    - fakeroot
#
#matrix:
#  allow_failures:
#    - env: ARTISAN_OS=rpi
#  include:
#  - os: osx
#    osx_image: xcode10.1 # Xcode 10.1, macOS 10.13
#    python: 3.8
#    language: generic
#    before_cache:
#      # - brew cleanup
#      - rm -f "$HOME/Library/Caches/pip/log/debug.log"
#    cache:
#      # As for now travis caches only "$HOME/.cache/pip"
#      # https://docs.travis-ci.com/user/caching/#pip-cache
#      pip: false
#      directories:
#      - $HOME/Library/Caches/pip    
#    env:
#      - ARTISAN_OS=osx
#      - HOMEBREW_NO_INSTALL_CLEANUP=1
#      - HOMEBREW_NO_ANALYTICS=1
#      - MACOSX_DEPLOYMENT_TARGET=10.13
#  - os: linux
#    python: 3.8 # NOTE: on update, update also the var PYTHON_PATH in src/build-linux.sh
#    dist: xenial
#    cache:
#      - pip
#      - bundler
#    env:
#      - ARTISAN_OS=linux
#  - os: linux
#    language: generic
#    dist: xenial
#    env:
#      ARTISAN_OS=rpi
#
#install:
#  - export GIT_VERSION=`git rev-parse --verify --short HEAD 2>/dev/null|| echo "???"`
#  - sed -i'' -e "s/__revision__ = '0'/__revision__ = '$GIT_VERSION'/" src/artisanlib/__init__.py
#  - .travis/install-${ARTISAN_OS}.sh
#  
#before_script:
#  - ulimit -c unlimited -S
#
#after_failure:
#  - find .  -name "core*"
#  - file src/core
#  - gdb -c src/core `which python3` -ex "thread apply all bt" -ex "set pagination 0" -batch
#
#script:
#  - .travis/script-${ARTISAN_OS}.sh
#
##after_success:
##  - cd src
##  - curl -L -O https://github.com/probonopd/uploadtool/raw/master/upload.sh
##  - export UPLOADTOOL_BODY="WARNING pre-release builds may not work. Use at your own risk."
##  - if [ "$ARTISAN_OS" = "osx" ]; then bash upload.sh artisan*.dmg; fi
##  - if [ "$ARTISAN_OS" = "rpi" ]; then bash upload.sh artisan*.deb; fi
##  - if [ "$ARTISAN_OS" = "linux" ]; then bash upload.sh artisan*.rpm artisan*.deb; fi 
#
 

