version: '2.4.3.{build}’

platform: macos

# Do not build on tags (GitHub only)
skip_tags: true

branches:
  only:
    - master

#environment:
#  GITHUB_TOKEN:
#    secure: 9UB76Z8mCWYt1u7Ci2fPVNiI3iK3LzTuIPhtNGBbxKP7YOPaUuq2yHxRjIfRPEAx
#  UPLOADTOOL_BODY:
#    "WARNING: pre-release builds may not work. Use at your own risk.”


environment:
  - ARTISAN_OS=osx
  osx_image: xcode10.1 # Xcode 10.1, macOS 10.13
  python: 3.8
  language: generic

install:
  - export GIT_VERSION=`git rev-parse --verify --short HEAD 2>/dev/null|| echo "???"`
  - sed -i'' -e "s/__revision__ = '0'/__revision__ = '$GIT_VERSION'/" src/artisanlib/__init__.py
  - .travis/install-${ARTISAN_OS}.sh

build_script:
  - .travis/script-${ARTISAN_OS}.sh

